using System.Collections.Generic;

namespace CoursesDownloader.Common.ExtensionMethods
{
    public struct MkToEnChars
    {
        public static Dictionary<string, string> CharsMap = new Dictionary<string, string>
        {
            {"А", "A"},
            {"а", "a"},
            {"Б", "B"},
            {"б", "b"},
            {"В", "V"},
            {"в", "v"},
            {"Г", "G"},
            {"г", "g"},
            {"Д", "D"},
            {"д", "d"},
            {"Ѓ", "Gj"},
            {"ѓ", "gj"},
            {"Е", "E"},
            {"е", "e"},
            {"Ж", "Zh"},
            {"ж", "zh"},
            {"З", "Z"},
            {"з", "z"},
            {"Ѕ", "Dz"},
            {"ѕ", "dz"},
            {"И", "I"},
            {"и", "i"},
            {"Ј", "J"},
            {"ј", "j"},
            {"К", "K"},
            {"к", "k"},
            {"Л", "L"},
            {"л", "l"},
            {"Љ", "Lj"},
            {"љ", "lj"},
            {"М", "M"},
            {"м", "m"},
            {"Н", "N"},
            {"н", "n"},
            {"Њ", "Nj"},
            {"њ", "nj"},
            {"О", "O"},
            {"о", "o"},
            {"П", "P"},
            {"п", "p"},
            {"Р", "R"},
            {"р", "r"},
            {"С", "S"},
            {"с", "s"},
            {"Т", "T"},
            {"т", "t"},
            {"Ќ", "Kj"},
            {"ќ", "kj"},
            {"У", "U"},
            {"у", "u"},
            {"Ф", "F"},
            {"ф", "f"},
            {"Х", "H"},
            {"х", "h"},
            {"Ц", "C"},
            {"ц", "c"},
            {"Ч", "Ch"},
            {"ч", "ch"},
            {"Џ", "Dzh"},
            {"џ", "dzh"},
            {"Ш", "Sh"},
            {"ш", "sh"}
        };
    }
}